In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [1]:
#NLP- natural language processing
#nltk - natural toolkit
!pip install nltk

In [5]:
#text preprocessing steps
#1)convertin to lower case
#2)word tokenization
#3)Removal of punctuations
#4)removal of stop words
#5)Stemming or Lemmatization

In [6]:
#Text transformation step (ml canot work on word)
#word vectors
#1)CountVectorizer
#2)TF-IDF Vectorizer

In [7]:
#converting to lower case
w = "HELLO WORLD"
print(w.lower())

hello world


In [3]:
#word tokenization
#Convertion of sentences/para into list of words
from nltk import word_tokenize


In [4]:
text = """"India on Wednesday set aside ₹5.94 trillion for defence spending 
in this year’s budget, including a capital outlay of ₹1.62 trillion for the
military’s modernization, with the allocation 13% higher than that in last 
year’s budget estimates, and about 2% more compared to that in the revised 
estimates for 2022-23, documents showed
"""

In [5]:
words = word_tokenize(text)
print(len(words))
print(words)

LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/english.pickle

  Searched in:
    - 'C:\\Users\\anish/nltk_data'
    - 'C:\\Users\\anish\\anaconda3\\nltk_data'
    - 'C:\\Users\\anish\\anaconda3\\share\\nltk_data'
    - 'C:\\Users\\anish\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\anish\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - ''
**********************************************************************


In [14]:
import nltk
nltk.download('punkt')


[nltk_data] Error loading punkt: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


False

In [6]:
import nltk
nltk.download('punkt')

[nltk_data] Error loading punkt: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


False

In [ ]:
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
       pass
else:
     ssl._create_default_https_context = _create_unverified_https_context

nltk.download()

In [7]:
words = word_tokenize(text)
print(len(words))
print(words)

LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/english.pickle

  Searched in:
    - 'C:\\Users\\anish/nltk_data'
    - 'C:\\Users\\anish\\anaconda3\\nltk_data'
    - 'C:\\Users\\anish\\anaconda3\\share\\nltk_data'
    - 'C:\\Users\\anish\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\anish\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - ''
**********************************************************************


In [ ]:
#unique words
u_words = list(set(words))
print(len(u_words))
print(u_words)


In [8]:
#Removal of puctuations
#a)using string
import string
punc = string.punctuation
print(punc)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [ ]:
rm_punc_words = [i for i words if i not in punc]
print(rm_punc_words)

In [9]:
#b)using Regex
import re

In [ ]:
#^A-Za-z0-9 - Anyhting startin with A-z ,a-z or 0-9 replacse wiht " " int words
rm_punc_words2 = re.sub(['^A-Za-z0-9]',' ',text)
print(rm_punc_words2)

In [10]:
#3)Removing stop words
#stop words are connecting words that do not relay any significant meanin as far
#as something are concenrned .One of the preprocessing step involves in stop words

In [11]:
from nltk.corpus import stopwords

In [ ]:
sw  = stopwords.words('English')
print(sw)   #printin stop words

In [ ]:
sw_rem = [i for i in rm_punc_words if i not in sw]
print(sw_rem)  #printing words after removing stop words

In [ ]:
#Stemming - 
#1)converting words into their root forms walking ->walk
#2)Most of the words generated out of stemming are no dictionary recognizable


In [21]:
from nltk.stem import PorterStemmer,LancasterStemmer
ps = PorterStemmer()
ls = LancasterStemmer()

In [22]:
w = ['troubled','everything','careless','exception','useful','happiness','commencement',
    'capability','suspicious','lovely','greenish','performance','independence','noicy',
    'membership','boldly','neighborhood','imformative','likewise','towards']
pstem = [ps.stem(i) for i in w]
print(pstem)


['troubl', 'everyth', 'careless', 'except', 'use', 'happi', 'commenc', 'capabl', 'suspici', 'love', 'greenish', 'perform', 'independ', 'noici', 'membership', 'boldli', 'neighborhood', 'imform', 'likewis', 'toward']


In [24]:
lstem = [ls.stem(i) for i in w]
print(lstem)

['troubl', 'everyth', 'careless', 'exceiv', 'us', 'happy', 'com', 'cap', 'suspicy', 'lov', 'green', 'perform', 'independ', 'noicy', 'memb', 'bold', 'neighb', 'imform', 'likew', 'toward']


In [25]:
#Lemmetization
#1)converting words into their root forms walking ->walk
#2)Most of the words generated out of stemming are  dictionary recognizable


In [35]:
from nltk.stem import WordNetLemmatizer
lm = WordNetLemmatizer()

In [36]:
lem = [lm.lemmatize(i,'n') for i in w]
print(lem)

LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - 'C:\\Users\\anish/nltk_data'
    - 'C:\\Users\\anish\\anaconda3\\nltk_data'
    - 'C:\\Users\\anish\\anaconda3\\share\\nltk_data'
    - 'C:\\Users\\anish\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\anish\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


In [37]:
>>> import nltk
>>> nltk.download('wordnet')

[nltk_data] Error loading wordnet: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


False

In [38]:
#Text transformation step
#word vectorization- converting words into int or float

In [40]:
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
#1)CountVectorization
s = ["Avatar2 is one of the finest work of art",
    "The movie Avatar2 is the best movie ever",
    "Avatar2 ,the movie seems to be bit dragged",
    "Avatar2 gravitates the Indian vedic planetry concious connection"]

In [49]:
cv = CountVectorizer()
cv.fit(s)
cv_res = cv.transform(s).toarray()
print(cv_res)
print(len(cv.get_feature_names_out()))
print(cv.get_feature_names_out())

[[1 1 0 0 0 0 0 0 0 1 0 0 1 0 2 1 0 0 1 0 0 1]
 [0 1 0 1 0 0 0 0 1 0 0 0 1 2 0 0 0 0 2 0 0 0]
 [0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 0]
 [0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 1 0 1 0]]
22
['art' 'avatar2' 'be' 'best' 'bit' 'concious' 'connection' 'dragged'
 'ever' 'finest' 'gravitates' 'indian' 'is' 'movie' 'of' 'one' 'planetry'
 'seems' 'the' 'to' 'vedic' 'work']


In [51]:
df_cv = pd.DataFrame(cv_res,columns=cv.get_feature_names_out())

In [52]:
df_cv

art  avatar2  be  best  bit  concious  connection  dragged  ever  finest  \
0    1        1   0     0    0         0           0        0     0       1   
1    0        1   0     1    0         0           0        0     1       0   
2    0        1   1     0    1         0           0        1     0       0   
3    0        1   0     0    0         1           1        0     0       0   

   ...  is  movie  of  one  planetry  seems  the  to  vedic  work  
0  ...   1      0   2    1         0      0    1   0      0     1  
1  ...   1      2   0    0         0      0    2   0      0     0  
2  ...   0      1   0    0         0      1    1   1      0     0  
3  ...   0      0   0    0         1      0    1   0      1     0  

[4 rows x 22 columns]

In [53]:
#2)TF-IDF vectorizer
#TF - term Frequency
#IDF - Inverse Document Frequency
#TF-IDF - TF+IDF


In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [55]:
tfidf = TfidfVectorizer()
tfidf.fit(s)
tfidf_res = tfidf.transform(s).toarray()
print(tfidf_res)
print(len(tfidf.get_feature_names_out()))
print(tfidf.get_feature_names_out())

[[0.330297   0.17236268 0.         0.         0.         0.
  0.         0.         0.         0.330297   0.         0.
  0.26040995 0.         0.660594   0.330297   0.         0.
  0.17236268 0.         0.         0.330297  ]
 [0.         0.2051641  0.         0.39315406 0.         0.
  0.         0.         0.39315406 0.         0.         0.
  0.30996717 0.61993435 0.         0.         0.         0.
  0.41032819 0.         0.         0.        ]
 [0.         0.21014969 0.4027079  0.         0.4027079  0.
  0.         0.4027079  0.         0.         0.         0.
  0.         0.31749953 0.         0.         0.         0.4027079
  0.21014969 0.4027079  0.         0.        ]
 [0.         0.20398387 0.         0.         0.         0.39089239
  0.39089239 0.         0.         0.         0.39089239 0.39089239
  0.         0.         0.         0.         0.39089239 0.
  0.20398387 0.         0.39089239 0.        ]]
22
['art' 'avatar2' 'be' 'best' 'bit' 'concious' 'connection' 'dragg